dependencies:
  default:
    main:
    - bemenu-wayland
    - bluez
    - bluez-utils
    - brightnessctl
    - grim
    - otf-font-awesome
    - playerctl
    - slurp
    - sway
    - swaybg
    - swayidle
    - swaylock
    - waybar
tags:
  laptop:
    dotfiles_dir: dotfiles-laptop
  desktop:
    dotfiles_dir: dotfiles-desktop
