git submodule add ./config/awesome/obvious https://github.com/hoelzro/obvious.git
git submodule add ./vim/vimfolder/bundle/file-line https://github.com/bogado/file-line
git submodule add ./vim/vimfolder/bundle/fugitive https://github.com/tpope/vim-fugitive
git submodule add ./vim/vimfolder/bundle/vim-toml https://github.com/cespare/vim-toml.git
git submodule add ./vim/vimfolder/bundle/nerdtree https://github.com/scrooloose/nerdtree.git
git submodule add ./vim/vimfolder/bundle/syntastic https://github.com/scrooloose/syntastic.git
git submodule add ./vim/vimfolder/bundle/neocomplete.vim https://github.com/Shougo/neocomplete.vim
git submodule add ./vim/vimfolder/bundle/valgrind.vim https://github.com/vim-scripts/valgrind.vim
git submodule add ./vim/vimfolder/bundle/tagbar https://github.com/majutsushi/tagbar
git submodule add ./vim/vimfolder/bundle/vimproc.vim https://github.com/Shougo/vimproc.vim.git
git submodule add ./vim/vimfolder/bundle/cscope-maps https://github.com/joe-skb7/cscope-maps.git
git submodule add ./vim/vimfolder/bundle/rust.vim https://github.com/rust-lang/rust.vim.git
git submodule add ./vim/vimfolder/bundle/vim-distinguished https://github.com/lokaltog/vim-distinguished.git
git submodule add ./vim/vimfolder/bundle/vim-marching https://github.com/osyo-manga/vim-marching.git
git submodule add ./vim/vimfolder/bundle/buffergator https://github.com/jeetsukumaran/vim-buffergator
git submodule add ./vim/vimfolder/bundle/vim-vividchalk https://github.com/tpope/vim-vividchalk
git submodule add ./vim/vimfolder/bundle/vim-airline https://github.com/vim-airline/vim-airline
git submodule add ./vim/vimfolder/bundle/ctrlp https://github.com/ctrlpvim/ctrlp.vim
git submodule add ./zsh/zshfolder/prompts/zsh-git-prompt https://github.com/olivierverdier/zsh-git-prompt.git
git submodule add ./zsh/zshfolder/zsh-config https://github.com/rust-lang/zsh-config.git
