common_deps:
- cmake
- emacs
- fd
- libvterm
- noto-fonts-emoji
- python-black
- python-isort
- python-pyflakes
- python-pytest
- rustup
- shellcheck
- shfmt
- stylelint
- tidy
- ttf-firacode-nerd
- ttf-nerd-fonts-symbols-mono
- ty
- uv
has_submodules: true
