enabled_default: true
dependencies:
  default:
    main:
    - cmake
    - emacs-wayland
    - fd
    - libvterm
    - noto-fonts-emoji
    - python-black
    - python-isort
    - python-pyflakes
    - python-pytest
    - rustup
    - shellcheck
    - shfmt
    - tidy
    - ttf-firacode-nerd
    - ttf-nerd-fonts-symbols-mono
    - ty
    - uv
submodules: true
