# The following lines were added by compinstall
zstyle :compinstall filename '/home/sindre/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
# End of lines configured by zsh-newuser-install

# Load custom prompts
source ~/workspace/system/zsh/zshfolder/prompts/zsh-git-prompt/zshrc.sh
PROMPT='%B%~%b$(git_super_status) %# '

# Set editor
export EDITOR=vim

export TERMINAL=xfce4-terminal

# Virtualenvwrapper
export WORKON_HOME=~/env
source "/usr/bin/virtualenvwrapper.sh"

# Path
export PATH="$PATH:/home/sindre/bin/:/home/sindre/.vimpkg/bin:/home/sindre/.cargo/bin"

# Man
man() {
    env LESS_TERMCAP_mb=$'\E[01 ; 31m' \
        LESS_TERMCAP_md=$'\E[01 ; 38 ; 5 ; 74m' \
        LESS_TERMCAP_md=$'\E[0m' \
        LESS_TERMCAP_md=$'\E[0m' \
        LESS_TERMCAP_md=$'\E[38 ; 5 ; 246m' \
        LESS_TERMCAP_md=$'\E[0m' \
        LESS_TERMCAP_md=$'\E[04 ; 38 ; 5 ; 146m' \
        man "$@"
}
